CREATE TABLE IF NOT EXISTS COMPANYS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SLOGAN VARCHAR(256),
	TEL VARCHAR(16),
	PO_BOX VARCHAR(10),
	ADDRESS VARCHAR(256),
	LOGO_URI VARCHAR(512)
);